### ISSUE TITLE
Bug: Events are not Read

### ISSUE THREAD

**Issue by kodeine** [PrestaShopCorp/nestjs-geteventstore#98]
I wasnt able to read the events in my app i thought my app broke after updating to use latest version of this package but then i gave a try running `examples` in this package and the bug actually exists. 

Events are being written properly but not Read. Following is the output from examples, notice the saga never runs because it couldn't read event.

![image](https://user-images.githubusercontent.com/8620059/143521583-1432f9b7-50b0-49df-be51-1f91cbef1886.png)

**Comment by kodeine** [comment]
@jdharandas would you be able to help me figure this out?

**Comment by jdharandas** [comment]
Hello, @kodeine. It seems that the WriteEventsPrepublishService is being included with the read module, but it shouldn't. This is being fixed in [5.1.x](https://github.com/PrestaShopCorp/nestjs-geteventstore/pull/100) as a side effect, as we have removed that dependency for that service, but we should patch it in 5.0.* too.

**Comment by kodeine** [comment]
@jdharandas i tried with the new PR #100  you have but events are still not being read.

**Comment by kodeine** [comment]
@jdharandas any idea when there will be a fix for reading events on latest version?

**Comment by jdharandas** [comment]
@kodeine I won't be able to take a look at this until January the 10th (more or less)

**Comment by kodeine** [comment]
Hello,

is there any updates on this?

**Comment by kodeine** [comment]
@AlexandreDecollas @Vinceveve @jdharandas 
Any idea when this will be fixed? Also, class `EventService` is not exportable so if we need to use `getProjectionState` method from `EventStore` we cannot.

**Comment by AlexandreDecollas** [comment]
Hi here, I cannot reproduce the error, could you provide a example code that reproduce this issue please? (btw, I added all missing exports on this lib)

**Comment by kodeine** [comment]
@AlexandreDecollas 
so i ran the examples/ folder again and following is the output.
I know its related to the DTO but looks like example folder isnt working.

**EDIT** PR #112 fixes this DTO issue but subscriptions are still not working

<img width="767" alt="image" src="https://user-images.githubusercontent.com/8620059/159800628-e149805f-cc6e-43e3-91a9-5d7ba153ad41.png">

<img width="926" alt="image" src="https://user-images.githubusercontent.com/8620059/159800587-d5ac239c-024b-43fd-9067-5b7801203476.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/8620059/159800867-01465625-8272-4e0f-9947-9c501a9cf041.png">

<img width="935" alt="image" src="https://user-images.githubusercontent.com/8620059/159800892-03abf9e5-1c50-4e1a-87d7-6c08eaa20821.png">

<img width="936" alt="image" src="https://user-images.githubusercontent.com/8620059/159800922-e4d60690-e177-463b-a42a-3e2e44e1a07f.png">

**Comment by kodeine** [comment]
@AlexandreDecollas @Vinceveve 
After fixing the dto issue, subscriptions are not working and events are not being read. 
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/8620059/162592221-1100383b-3494-439b-bd4b-4247799b7998.png">

Root case is payload is coming as undefined, 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/8620059/162600102-40b26fce-cd1f-4b77-bc14-249ab57a8e5e.png">

also, `persistentSubscription.on('data'...` is suppose to return a single object not two.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/8620059/162600130-13c2cc5e-f27d-4ebc-853f-b327b86e60a0.png">

here `this.eventBus` comes `undefined` as well.
<img width="471" alt="image" src="https://user-images.githubusercontent.com/8620059/162600234-c6c424b9-e77f-4257-8a54-3acdaac85979.png">

**Comment by kodeine** [comment]
@jokesterfr since you added the label as a bug, were you able to test this at your end as well?

**Comment by jdharandas** [comment]
@kodeine 5.x is not really working, I have tested it and it has a lot of bugs (not only this one). As @AlexandreDecollas is the "owner" of this version, I will try to work with him to create the fixes, but at this moment I am working with @Rzial in a 6.x that fixes those bugs and adds new functionalities (fex: write event bus middlewares).

**Comment by kodeine** [comment]
@jdharandas thank you for the update, i was going crazy testing this i thought i was making some mistake unknowingly but then i started digging into the code and found issues. Thanks a lot for your input. I will wait for v6, is it going to be in this repo or somewhere else? I actually was going live with my product and wanted to make sure i am on latest versions but seems like i cant use eventstore 20.10.x. If you have any timeline for v6 or fixes for this v5, please do let me know. Once again, thank you again.
